POST http://localhost:3000/api/check-card

###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "123456",
    "userId": "1b60e4beb3e6f269"
}

###

POST http://localhost:3000/api/delete-user
Content-Type: application/json

{
    "userId": "1b60e4beb3e6f269"
}

###

POST http://localhost:3000/api/teste
Content-Type: application/json

{
    "email": "teste@gmail.com"
}